apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: basic-template
  title: Template Básico
  description: Um template básico para projetos
spec:
  owner: user:bonett
  type: service
  parameters:
    - title: Informações do Projeto
      required:
        - name
      properties:
        name:
          title: Nome do Projeto
          type: string
          description: Nome único do projeto
  steps:
    - id: fetch-base
      name: Buscar Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
    
    - id: publish
      name: Publicar no GitHub
      action: publish:github
      input:
        repoUrl: github.com?owner=bonettdreans&repo=${{ parameters.name }}
        
    - id: register
      name: Registrar no Catálogo
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'
